#! /bin/bash
#
#$Author: ee364f04 $ Yiyi Chen
#$Date: 2016-01-16 10:39:54 -0500 (Sat, 16 Jan 2016) $
#$Revision: 85183 $ 
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364f04/Lab00/Script1 $ 
#$Id: Script1 85183 2016-01-16 15:39:54Z ee364f04 $ A combination of the above keywords

Num_Of_Param=$#
Param_Values=$@
echo "The program received $Num_Of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0