#! /bin/bash
#
#$Author: ee364f04 $ Yiyi Chen
#$Date: 2016-01-16 10:51:15 -0500 (Sat, 16 Jan 2016) $
#$Revision: 85184 $ 
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364f04/Lab00/Script2 $ 
#$Id: Script2 85184 2016-01-16 15:51:15Z ee364f04 $ A combination of the above keywords

Num_Of_Param=$#
Param_Values=$@
for (( I=$Param_Values; I >=0; I--))
do
    echo $I
done
exit 0