#! /bin/bash
#
#$Author: ee364f04 $ Yiyi Chen
#$Date: 2016-01-16 11:00:25 -0500 (Sat, 16 Jan 2016) $
#$Revision: 85185 $ 
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364f04/Lab00/Script3 $ 
#$Id: Script3 85185 2016-01-16 16:00:25Z ee364f04 $ A combination of the above keywords

Num_Of_Param=$#
Param_Values=$@
for (( I=$Param_Values; I >=0; I--))
do
    if (($I%3== 0))
    then
	echo $I
    fi
done
exit 0