#! /bin/bash
#
#$Author: ee364f04 $ Yiyi Chen
#$Date: 2016-01-16 10:03:28 -0500 (Sat, 16 Jan 2016) $
#$Revision: 85182 $ 
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364f04/Lab00/testheader $ 
#$Id: testheader 85182 2016-01-16 15:03:28Z ee364f04 $ A combination of the above keywords

